#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

mkdir -p $DESTDIR/lib/udev/rules.d/
for rules in 60-persistent-storage-hptblock.rules; do
  if   [ -e /etc/udev/rules.d/$rules ]; then
    cp -p /etc/udev/rules.d/$rules $DESTDIR/lib/udev/rules.d/
  elif [ -e /lib/udev/rules.d/$rules ]; then
    cp -p /lib/udev/rules.d/$rules $DESTDIR/lib/udev/rules.d/
  fi
done

