---

# line_title can be a max of 10-12 characters (depending on character width)

lines:

  - description: Alex Pollak
    extension: 110
    line_title: Alex P
    phone_mac: "64:16:7F:7B:01:AC"
    phone_ipv4: 10.1.22.21

  - description: Marc Jacquart
    extension: 111
    line_title: Marc J
    phone_mac: "AA:AA:AA:AA:AA:00"
    phone_ipv4: 10.1.22.26

  - description: Wael Farah
    extension: 112
    line_title: Wael F
    phone_mac: "AA:AA:AA:AA:AA:01"
    phone_ipv4: 10.1.22.27

  - description: Paul Coldren
    extension: 114
    line_title: Paul C
    phone_mac: "64:16:7F:58:ED:34"
    phone_ipv4: 10.1.22.20

  - description: Mark Masters
    extension: 120
    line_title: Mark M
    phone_mac: "64:16:7F:58:CF:83"
    phone_ipv4: 10.1.22.22

  - description: Carol Shumaker
    extension: 121
    line_title: Carol S
    phone_mac: "AA:AA:AA:AA:AA:02"
    phone_ipv4: 10.1.22.28

  - description: Research Office
    extension: 122
    line_title: Research Ofc
    phone_mac: "AA:AA:AA:AA:AA:0E"
    phone_ipv4: 10.1.22.40

  - description: Student Desk 1
    extension: 130
    line_title: Student 1
    phone_mac: "AA:AA:AA:AA:AA:03"
    phone_ipv4: 10.1.22.29

  - description: Student Desk 2
    extension: 131
    line_title: Student 2
    phone_mac: "AA:AA:AA:AA:AA:04"
    phone_ipv4: 10.1.22.30

  - description: Conference Room
    extension: 140
    line_title: Conf Room
    phone_mac: "AA:AA:AA:AA:AA:05"
    phone_ipv4: 10.1.22.31

  - description: Electronics Workshop
    extension: 143
    line_title: Elec Wkshp
    phone_mac: "AA:AA:AA:AA:AA:06"
    phone_ipv4: 10.1.22.32

  - description: Signal Processing Room
    extension: 145
    line_title: SPR
    phone_mac: "AA:AA:AA:AA:AA:07"
    phone_ipv4: 10.1.22.33

  - description: Lab 1
    extension: 150
    line_title: Lab 1
    phone_mac: "AA:AA:AA:AA:AA:08"
    phone_ipv4: 10.1.22.34

  - description: Lab 2
    extension: 152
    line_title: Lab 2
    phone_mac: "AA:AA:AA:AA:AA:09"
    phone_ipv4: 10.1.22.35

  - description: Lab 2 Clean Room
    extension: 153
    line_title: Lab 2 Cln Rm
    phone_mac: "AA:AA:AA:AA:AA:0A"
    phone_ipv4: 10.1.22.36

  - description: UPS Shed
    extension: 160
    line_title: UPS Shed
    phone_mac: "AA:AA:AA:AA:AA:0B"
    phone_ipv4: 10.1.22.37

  - description: Main Workshop
    extension: 161
    line_title: Main Wkshp
    phone_mac: "AA:AA:AA:AA:AA:0C"
    phone_ipv4: 10.1.22.38

  - description: Chime Container
    extension: 163
    line_title: Chime
    phone_mac: "AA:AA:AA:AA:AA:0D"
    phone_ipv4: 10.1.22.39

  - description: Dorm Library
    extension: 210
    line_title: Dorm Library
    phone_mac: "64:16:7F:7A:FE:35"
    phone_ipv4: 10.1.22.23

  - description: Lassen House
    extension: 250
    line_title: Lassen
    phone_mac: "64:16:7F:58:DB:93"
    phone_ipv4: 10.1.22.24

  - description: Hat Creek House
    extension: 260
    line_title: Hat Creek
    phone_mac: "64:16:7F:58:D5:DF"
    phone_ipv4: 10.1.22.25

  - description: Spare 01
    extension: 171
    line_title: Spare 01
    phone_mac: "AA:AA:AA:AA:AA:10"
    phone_ipv4: 10.1.22.41
    hide_from_directory: True

  - description: Spare 02
    extension: 172
    line_title: Spare 02
    phone_mac: "AA:AA:AA:AA:AA:11"
    phone_ipv4: 10.1.22.42
    hide_from_directory: True

  - description: Spare 03
    extension: 173
    line_title: Spare 03
    phone_mac: "AA:AA:AA:AA:AA:12"
    phone_ipv4: 10.1.22.43
    hide_from_directory: True

  - description: Spare 04
    extension: 174
    line_title: Spare 04
    phone_mac: "AA:AA:AA:AA:AA:13"
    phone_ipv4: 10.1.22.44
    hide_from_directory: True

  - description: Spare 05
    extension: 175
    line_title: Spare 05
    phone_mac: "AA:AA:AA:AA:AA:14"
    phone_ipv4: 10.1.22.45
    hide_from_directory: True

  - description: Spare 06
    extension: 176
    line_title: Spare 06
    phone_mac: "AA:AA:AA:AA:AA:15"
    phone_ipv4: 10.1.22.46
    hide_from_directory: True

  - description: Spare 07
    extension: 177
    line_title: Spare 07
    phone_mac: "AA:AA:AA:AA:AA:16"
    phone_ipv4: 10.1.22.47
    hide_from_directory: True

  - description: Spare 08
    extension: 178
    line_title: Spare 08
    phone_mac: "AA:AA:AA:AA:AA:17"
    phone_ipv4: 10.1.22.48
    hide_from_directory: True

  - description: Spare 09
    extension: 179
    line_title: Spare 09
    phone_mac: "AA:AA:AA:AA:AA:18"
    phone_ipv4: 10.1.22.49
    hide_from_directory: True

  - description: Spare 10
    extension: 180
    line_title: Spare 10
    phone_mac: "AA:AA:AA:AA:AA:19"
    phone_ipv4: 10.1.22.50
    hide_from_directory: True

  - description: Spare 11
    extension: 181
    line_title: Spare 11
    phone_mac: "AA:AA:AA:AA:AA:1A"
    phone_ipv4: 10.1.22.51
    hide_from_directory: True

  - description: Spare 12
    extension: 182
    line_title: Spare 12
    phone_mac: "AA:AA:AA:AA:AA:1B"
    phone_ipv4: 10.1.22.52
    hide_from_directory: True

  - description: Spare 13
    extension: 183
    line_title: Spare 13
    phone_mac: "AA:AA:AA:AA:AA:1C"
    phone_ipv4: 10.1.22.53
    hide_from_directory: True

  - description: Spare 14
    extension: 184
    line_title: Spare 14
    phone_mac: "AA:AA:AA:AA:AA:1D"
    phone_ipv4: 10.1.22.54
    hide_from_directory: True

  - description: Spare 15
    extension: 185
    line_title: Spare 15
    phone_mac: "AA:AA:AA:AA:AA:1E"
    phone_ipv4: 10.1.22.55
    hide_from_directory: True


groups:

  - description: "*Main Lab All*"
    extension: 310

  - description: "*Lab 1 All*"
    extension: 311

  - description: "*Lab 2 All*"
    extension: 312

  - description: "*UPS Shed All*"
    extension: 313

  - description: "*Main Workshop All*"
    extension: 314

  - description: "*Chime All*"
    extension: 316

  - description: "*Dorm Common*"
    extension: 320

  - description: "*Lassen House Common*"
    extension: 321

  - description: "*Hat Creek House Common*"
    extension: 322

  - description: "*All Residence Common*"
    extension: 324

  - description: "*External Calls - Day*"
    extension: 330
    hide_from_directory: True

  - description: "*Main Lab Obs*"
    extension: 340

  - description: "*Main Lab Offices*"
    extension: 341

  - description: "*Main Lab Student*"
    extension: 342

  - description: "*Main Lab Common*"
    extension: 343

  - description: "***ALL HCRO PHONES***"
    extension: 510

  - description: "***ALL Work Phones***"
    extension: 511

  - description: "***ALL Residence Phones***"
    extension: 512

  - description: "****PAGE ALL HCRO****"
    extension: 710

  - description: "****PAGE ALL WORK****"
    extension: 711

  - description: "****PAGE ALL RESIDENCE****"
    extension: 712
